### ISSUE TITLE
Fix "Total Chapters Read"

### ISSUE THREAD

**Issue by TheInternetUse7** [CosmicPredator/chibi-cli#1]
![image](https://github.com/user-attachments/assets/c0602c42-2824-41a7-8902-cc8c534b6bcc)
![image](https://github.com/user-attachments/assets/18558bb7-fa28-447a-a22c-d3504910308d)

**Comment by CosmicPredator** [comment]
Found the issue, now fixing 
https://github.com/CosmicPredator/chibi-cli/blob/8c8781a9f0df52d1443a8d4b521f4aa5addc26b4/internal/profile.go#L31

**Comment by mist8kengas** [comment]
#2

**Comment by CosmicPredator** [comment]
Closing the PR as the issue has been fixed
