### ISSUE TITLE
[✨] Add an updater

### ISSUE THREAD

**Issue by TheInternetUse7** [CosmicPredator/chibi-cli#5]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add some sort of self-updater that checks for new versions and replaces the existing executable.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by CosmicPredator** [comment]
I'm planning to publish the app to package manager such as winget, homebrew, apt, snap, flathub etc., so that you can get auto update feature. Please wait 😁

**Comment by CosmicPredator** [comment]
https://github.com/CosmicPredator/chibi-cli/releases/tag/1.0.2
