### ISSUE TITLE
Commit `go.sum` to repository

### ISSUE THREAD

**Issue by Fuwn** [CosmicPredator/chibi-cli#6]
Since Chibi doesn't vendor its dependencies, a `go.sum` file would be useful and is generally a necessity when packaging for external package repositories.

The official Go development wiki also encourages everyone to commit their `go.sum`s: https://go.dev/wiki/Modules#should-i-commit-my-gosum-file-as-well-as-my-gomod-file.

I currently package Chibi in one of my Nix flakes, [Tsutsumi](https://github.com/Fuwn/tsutsumi), and I'm having to manually clone Chibi, generate a [`go.sum` file](https://github.com/Fuwn/tsutsumi/blob/main/pkgs/chibi-cli/go.sum), and patch it in for the [Nix module](https://github.com/Fuwn/tsutsumi/blob/main/pkgs/chibi-cli/default.nix) for each commit to ensure that Chibi will even build.

**Comment by CosmicPredator** [comment]
Sure,I'll include the `go.sum` file on the next commit. Also, meanwhile use `go mod tidy` as a workaround.

**Comment by CosmicPredator** [comment]
@Fuwn I have added the `go.sum` file in `develop` branch. Please refer to this commit- abdd62d23fec37f1093f5759572ca4d06a3c46ce.
